services:
  setup-framework:
    container_name: setup-framework
    env_file:
      - .env
    build:
      context: .
      dockerfile: .docker/Setup.Dockerfile
    image: setup-framework:latest
    command: python benchmark_runner.py --script-id setup-framework --benchmark-run 1 --run-id ABCDEF

  container-orchestrator:
    env_file:
      - .env
    build:
      context: .
      dockerfile: .docker/Orchestrator.Dockerfile
    image: container-orchestrator:latest
    command: python -m main

  db-scan-blob-storage:
    env_file:
      - .env
    build:
      context: .
      dockerfile: .docker/Query.Dockerfile
    image: db-scan-blob-storage:latest
    command: python benchmark_runner.py --script-id db-scan-blob-storage --benchmark-run 1 --run-id ABCDEF

  db-scan-postgis:
    env_file:
      - .env
    build:
      context: .
      dockerfile: .docker/Query.Dockerfile
    image: db-scan-postgis:latest
    command: python benchmark_runner.py --script-id db-scan-postgis --benchmark-run 1 --run-id ABCDEF

  bbox-filtering-advanced-duckdb:
    env_file:
      - .env
    build:
      context: .
      dockerfile: .docker/Query.Dockerfile
    image: bbox-filtering-advanced-duckdb:latest
    command: python benchmark_runner.py --script-id bbox-filtering-advanced-duckdb --benchmark-run 1 --run-id ABCDEF

  bbox-filtering-advanced-postgis:
    env_file:
      - .env
    build:
      context: .
      dockerfile: .docker/Query.Dockerfile
    image: bbox-filtering-advanced-postgis:latest
    command: python benchmark_runner.py --script-id bbox-filtering-advanced-postgis --benchmark-run 1 --run-id ABCDEF

  bbox-filtering-simple-local:
    env_file:
      - .env
    build:
      context: .
      dockerfile: .docker/Query.Dockerfile
    image: bbox-filtering-simple-local:latest
    command: python benchmark_runner.py --script-id bbox-filtering-simple-local --benchmark-run 1 --run-id ABCDEF

  bbox-filtering-simple-blob-storage:
    env_file:
      - .env
    build:
      context: .
      dockerfile: .docker/Query.Dockerfile
    image: bbox-filtering-simple-blob-storage:latest
    command: python benchmark_runner.py --script-id bbox-filtering-simple-blob-storage --benchmark-run 1 --run-id ABCDEF

  vector-tiles-single-tile-pmtiles:
    env_file:
      - .env
    build:
      context: .
      dockerfile: .docker/Query.Dockerfile
    image: vector-tiles-single-tile-pmtiles:latest
    command: python benchmark_runner.py --script-id vector-tiles-single-tile-pmtiles --benchmark-run 1 --run-id ABCDEF

  vector-tiles-single-tile-vmt:
    env_file:
      - .env
    build:
      context: .
      dockerfile: .docker/Query.Dockerfile
    image: vector-tiles-single-tile-vmt:latest
    command: python benchmark_runner.py --script-id vector-tiles-single-tile-vmt --benchmark-run 1 --run-id ABCDEF

  vector-tiles-100k-vmt:
    env_file:
      - .env
    build:
      context: .
      dockerfile: .docker/Query.Dockerfile
    image: vector-tiles-100k-vmt:latest
    command: python benchmark_runner.py --script-id vector-tiles-100k-vmt --benchmark-run 1 --run-id ABCDEF

  vmt-api-server:
    env_file:
      - .env
    build:
      context: .
      dockerfile: .docker/Api.Dockerfile
    ports:
      - "8000:8000"
    image: vmt-api-server:latest
    command: uvicorn src.presentation.endpoints.tile_server:app --host 0.0.0.0 --port 8000
